export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const BAD_CREDENTIALS = "BAD_CREDENTIALS";
export const SERVER_ERRORS = "SERVER_ERRORS";

export const SIGNUP_SUCCESSFULLY = "SIGNUP_SUCCESSFULLY";
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const USERNAME_TAKEN = "USERNAME_TAKEN";
export const BAD_REQUEST = "BAD_REQUEST";

export const LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY";


