export const CONNECT_TO_JANUS_SUCCESSFULLY = "CONNECT_TO_JANUS_SUCCESSFULLY";
export const FETCH_ALL_LIVESTREAMS_SUCCESSFULLY = "FETCH_ALL_LIVESTREAMS_SUCCESSFULLY";
export const FETCH_A_LIVESTREAM_SUCCESSFULLY = "FETCH_A_LIVESTREAM_SUCCESSFULLY";
export const LIVESTREAM_NOT_FOUND = "LIVESTREAM_NOT_FOUND"
export const CREATE_ROOM_SUCCESSFULLY = "CREATE_ROOM_SUCCESSFULLY";